### ISSUE TITLE
Encoding issue with Python 3.8

### ISSUE THREAD

**Issue by harlock974** [izivkov/GShockTimeServer#1]
Hi Izivkov,
Thank you for this smart program. I couldn't stand any more the awkward Casio android app...
When I tried your program I had got the following error :

`File "/home/xxxx/GShockTimeServer/src/gshocktimeserver/logger.py", line 10, in Logger
    logging.basicConfig(
  File "/usr/lib/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding
` 

It is because my Linux system run Python 3.8 and the encoding parameter has been added to Python 3.9.

For those with the same issue they just need to comment line 11 in file logger.py, this way :

`        #encoding='utf-8',`

Then it works perfectly well with Python 3.8.

**Comment by izivkov** [comment]
Thank you for providing the information. I have removed the ```encoding``` argument from the ```logger.py```, as you suggested. Now it should be compatible with Python 3.8.

This is where `anaconda` would be useful, but since this code can run on small devices like `raspberry pi zero`, I like to provide minimum configuration.

BTW, if you are looking for FOSS android program for the G-Shock, we also have [this](https://github.com/izivkov/CasioGShockSmartSync)

**Comment by izivkov** [comment]
Closing as done.

**Comment by izivkov** [comment]
Done
